SELECT DISTINCT(A.NUMPED)"N∫ PEDIDO",
       U.CODSUPERVISOR "SUPERV.",
       (U.CODUSUR || ' - ' || SUBSTR(U.NOME,4,9)) AS VENDEDOR,
       TO_CHAR(A.DATA, 'DD/MM') || ' ‡S ' || B.HORA||'H' AS ENVIO,
       B.DTLIBERA,
       
       (CASE WHEN A.POSICAO LIKE 'B' THEN A.POSICAO||'LOQUEADO' 
             WHEN A.POSICAO LIKE 'C' THEN A.POSICAO||'ANCELADO'
             WHEN A.POSICAO LIKE 'P' THEN A.POSICAO||'ENDENTE'
             ELSE A.POSICAO||'IBERADO' END) AS STATUS,
             
       'R$'||REPLACE(B.VLTOTAL, '.', ',') "VALOR R$", '|' "|",
       A.CODCLI|| ' - ' ||SUBSTR(D.CLIENTE,0,30) AS CLIENTE,
       
       (CASE WHEN B.OBS IS NULL THEN 'ANTIGO NO SISTEMA' 
             ELSE B.OBS END) AS "MOTIVO ANALISADO",
             
       (SELECT LISTAGG(C.MOTIVO, ' | ') WITHIN GROUP (ORDER BY C.MOTIVO DESC)
               FROM PONTUAL.PCBLOQUEIOSPEDIDO C 
               WHERE A.NUMPED = C.NUMPED) AS "MOTIVO SISTEMA"
               
FROM PONTUAL.PCPEDI A
    JOIN PONTUAL.PCPEDC B ON A.NUMPED = B.NUMPED
    JOIN PONTUAL.PCBLOQUEIOSPEDIDO C ON A.NUMPED = C.NUMPED
    JOIN PONTUAL.PCCLIENT D ON D.CODCLI = A.CODCLI 
    JOIN PONTUAL.PCUSUARI U ON U.CODUSUR = A.CODUSUR
WHERE A.DATA BETWEEN '26-nov-2023' AND '22-sep-2024'
    AND U.CODSUPERVISOR IN (2,8,9)--({CBBSUP})
    AND A.CODUSUR not IN (10)
    AND A.POSICAO NOT LIKE 'F' AND A.POSICAO NOT LIKE 'M' AND A.POSICAO NOT LIKE 'C'
ORDER BY "N∫ PEDIDO"

/* {CBBSUP}
SELECT DISTINCT CODSUPERVISOR COD,
       (CASE WHEN CODSUPERVISOR = 2 THEN 'ADAILTON'
             WHEN CODSUPERVISOR = 8 THEN 'VILMAR'
             WHEN CODSUPERVISOR = 9 THEN 'LEANDRO'
             ELSE 'INATIVO' END) SUPERVISOR
FROM PONTUAL.PCUSUARI
WHERE CODSUPERVISOR IN (2,8,9)
ORDER BY CODSUPERVISOR
*/

/* {RCA}
SELECT DISTINCT CODUSUR COD,
       SUBSTR(NOME,5,100) RCA
FROM PONTUAL.PCUSUARI
WHERE CODSUPERVISOR IN (2,8,9)--({CBBSUP})
AND NOME LIKE 'PMU%'
ORDER BY CODUSUR
*/ 489163

/* CONSULTA PARA GR¡FICO PIZZA
SELECT (CASE WHEN U.CODSUPERVISOR = 2 THEN 'ADAILTON'
             WHEN U.CODSUPERVISOR = 8 THEN 'VILMAR'
             WHEN U.CODSUPERVISOR = 9 THEN 'LEANDRO'
             ELSE 'INATIVO' END) SUPERVISOR,
      SUM(DISTINCT( B.VLTOTAL)) VALOR

FROM PONTUAL.PCPEDI A
    JOIN PONTUAL.PCPEDC B ON A.NUMPED = B.NUMPED
    JOIN PONTUAL.PCBLOQUEIOSPEDIDO C ON A.NUMPED = C.NUMPED
    JOIN PONTUAL.PCCLIENT D ON D.CODCLI = A.CODCLI 
    JOIN PONTUAL.PCUSUARI U ON U.CODUSUR = A.CODUSUR
WHERE A.DATA BETWEEN SYSDATE-14 AND SYSDATE
    AND U.CODSUPERVISOR IN (2,8,9)
    AND A.POSICAO NOT LIKE 'F' AND A.POSICAO NOT LIKE 'M' AND A.POSICAO NOT LIKE 'L'
GROUP BY U.CODSUPERVISOR
*/
--SELECT * FROM PCPEDC
