WITH VENDAS1 AS (
    SELECT A.CODPROD, SUM(A.QT) 
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'S' 
    AND A.DTMOV > TRUNC(SYSDATE, 'MM')
    AND A.DTMOV < SYSDATE+1
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
),

DEVOLUCOES1 AS (
    SELECT A.CODPROD, SUM(A.QT) 
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'ED' 
    AND A.DTMOV > TRUNC(SYSDATE, 'MM')
    AND A.DTMOV < SYSDATE+1
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
),

VENDAS2 AS (
    SELECT A.CODPROD, SUM(A.QT) 
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'S' 
    AND A.DTMOV >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') -- Primeiro dia do mês anterior
    AND A.DTMOV < TRUNC(SYSDATE, 'MM') -- Dia anterior ao Primeiro dia do mês atual
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
),

DEVOLUCOES2 AS (
    SELECT A.CODPROD, SUM(A.QT) 
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'ED' 
    AND A.DTMOV >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') -- Primeiro dia do mês anterior
    AND A.DTMOV < TRUNC(SYSDATE, 'MM') -- Dia anterior ao Primeiro dia do mês atual
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
),

VENDAS3 AS (
    SELECT A.CODPROD, SUM(A.QT) 
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'S' 
    AND A.DTMOV >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') -- Primeiro dia do mês anterior
    AND A.DTMOV < TRUNC(SYSDATE, 'MM') -- Dia anterior ao Primeiro dia do mês atual
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
),

DEVOLUCOES3 AS (
    SELECT A.CODPROD, SUM(A.QT) 
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'ED' 
    AND A.DTMOV >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') -- Primeiro dia do mês anterior
    AND A.DTMOV < TRUNC(SYSDATE, 'MM') -- Dia anterior ao Primeiro dia do mês atual
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
)

SELECT C.CODFORNEC "FORNECEDOR", 
    A.CODPROD,
    C.DESCRICAO, A.QTEST "ESTOQUE", 
    A.CUSTOULTENT "CUSTO + IMP.", 
    (A.VALORULTENT + VLULTPCOMPRA) / 2 "PREÇO",
    A.QTVENDMES1 "MÊS 1", A.QTVENDMES2 "MÊS 2", A.QTVENDMES3 "MÊS 3"
FROM PONTUAL.PCEST A
JOIN PONTUAL.PCPRODUT C ON A.CODPROD = C.CODPROD
JOIN PONTUAL.PCPRECO P ON A.CODPROD = P.CODPROD
WHERE A.CODFILIAL = 3
AND C.CODFORNEC IN :FORNECEDOR--({COMBOBOX1})
AND TO_DATE(A.DTULTENT, 'DD/MM/YY') > SYSDATE-120          
GROUP BY A.CODPROD, C.CODFORNEC, C.DESCRICAO, A.QTEST, A.CUSTOULTENT, A.VALORULTENT, VLULTPCOMPRA,A.QTVENDMES1, A.QTVENDMES2, A.QTVENDMES3
HAVING A.QTEST > 0
ORDER BY C.CODFORNEC, A.CODPROD
