WITH VENDAS1 AS (
    SELECT A.CODPROD, SUM(NVL(A.QT,0)) QT
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'S' 
    AND A.DTMOV > TRUNC(SYSDATE, 'MM')
    AND A.DTMOV < SYSDATE+1
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
),

DEVOLUCOES1 AS (
    SELECT A.CODPROD, SUM(NVL(A.QT,0)) QT
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'ED' 
    AND A.DTMOV > TRUNC(SYSDATE, 'MM')
    AND A.DTMOV < SYSDATE+1
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
),

VENDAS2 AS (
    SELECT A.CODPROD, SUM(NVL(A.QT,0)) QT
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'S' 
    AND A.DTMOV >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') -- Primeiro dia do mês anterior
    AND A.DTMOV < TRUNC(SYSDATE, 'MM') -- Dia anterior ao Primeiro dia do mês atual
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
),

DEVOLUCOES2 AS (
    SELECT A.CODPROD, SUM(NVL(A.QT,0)) QT
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'ED' 
    AND A.DTMOV >= TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') -- Primeiro dia do mês anterior
    AND A.DTMOV < TRUNC(SYSDATE, 'MM') -- Dia anterior ao Primeiro dia do mês atual
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
),

VENDAS3 AS (
    SELECT A.CODPROD, SUM(NVL(A.QT,0)) QT
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'S' 
    AND A.DTMOV >= TRUNC(ADD_MONTHS(SYSDATE, -2), 'MM') -- Primeiro dia de dois meses atrás
    AND A.DTMOV < TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') -- Primeiro dia do mês anterior
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
),

DEVOLUCOES3 AS (
    SELECT A.CODPROD, SUM(NVL(A.QT,0)) QT
    FROM PONTUAL.PCMOV A 
    WHERE A.CODOPER = 'ED' 
    AND A.DTMOV >= TRUNC(ADD_MONTHS(SYSDATE, -2), 'MM') -- Primeiro dia de dois meses atrás
    AND A.DTMOV < TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') -- Primeiro dia do mês anterior
    AND A.DTCANCEL IS NULL
    AND A.CODCLI IS NOT NULL
    GROUP BY A.CODPROD
)

SELECT C.CODFORNEC "FORNECEDOR", 
    A.CODPROD,
    C.DESCRICAO, A.QTEST "ESTOQUE", 
    A.CUSTOULTENT "CUSTO + IMP.", 
    (A.VALORULTENT + VLULTPCOMPRA) / 2 "PREÇO",
    V3.QT - D3.QT "MÊS 1", 
    V2.QT - D2.QT "MÊS 2", 
    V1.QT - D1.QT "MÊS 3"
FROM PONTUAL.PCEST A
JOIN PONTUAL.PCPRODUT C ON A.CODPROD = C.CODPROD
JOIN PONTUAL.PCPRECO P ON A.CODPROD = P.CODPROD
LEFT JOIN VENDAS1 V1 ON A.CODPROD = V1.CODPROD
LEFT JOIN DEVOLUCOES1 D1 ON V1.CODPROD = D1.CODPROD
LEFT JOIN VENDAS2 V2 ON A.CODPROD = V2.CODPROD
LEFT JOIN DEVOLUCOES2 D2 ON V2.CODPROD = D2.CODPROD
LEFT JOIN VENDAS3 V3 ON A.CODPROD = V3.CODPROD
LEFT JOIN DEVOLUCOES3 D3 ON V3.CODPROD = D3.CODPROD
WHERE A.CODFILIAL = 3
AND C.CODFORNEC = 1841
AND TO_DATE(A.DTULTENT, 'DD/MM/YY') > SYSDATE-120          
GROUP BY A.CODPROD, C.CODFORNEC, C.DESCRICAO, A.QTEST, A.CUSTOULTENT, A.VALORULTENT, VLULTPCOMPRA,A.QTVENDMES1, A.QTVENDMES2, A.QTVENDMES3, V1.QT, V2.QT, V3.QT, D1.QT, D2.QT, D3.QT
ORDER BY C.CODFORNEC, A.CODPROD
