WITH ROTA AS (
    SELECT 
        CODUSUR,
        DIASEMANA,
        CODCLI,
        PERIODICIDADE,
        DTPROXVISITA,
        NUMSEMANA,
        DTFINAL,
        DTINICIO,
        CODCOMPROMISSO,
        DIAFIXO 
    FROM 
        PONTUAL.PCROTACLI 
),

PEDIDO_POSIT AS (
    SELECT 
        DISTINCT(CODCLI),
        CODUSUR,
        NUMPED,
        CODPROD
    FROM 
        PONTUAL.PCPEDI
    WHERE
        DATA BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(SYSDATE)
    AND
        CODPROD IN (17528, 18157, 17484, 17506, 17462, 17507, 17517, 18446, 18035, 17932, 18079, 18448, 18447)
),

PEDIDO_SIS AS (
    SELECT 
        DISTINCT(NUMPED),
        CODUSUR,
        CODCLI
    FROM 
        PONTUAL.PCPEDI
    WHERE
        DATA BETWEEN TRUNC(SYSDATE, 'IW') AND TRUNC(SYSDATE, 'IW') + 6  -- TRUNC(SYSDATE, 'IW') retorna o primeiro dia da semana
),

PEDIDO_FAT AS (
    SELECT 
        DISTINCT(NUMPED),
        CODUSUR,
        CODCLI
    FROM 
        PONTUAL.PCPEDC
    WHERE
        DATA BETWEEN TRUNC(SYSDATE, 'IW') AND TRUNC(SYSDATE, 'IW') + 6  -- TRUNC(SYSDATE, 'IW') retorna o primeiro dia da semana
    AND
        POSICAO LIKE 'F'
)

SELECT
    DISTINCT(CLI.CODCLI)
    ,CLI.CLIENTE
    ,(CASE WHEN CLI.CODCLI IN (SELECT PS.CODCLI FROM PEDIDO_SIS PS WHERE PS.CODCLI = CLI.CODCLI) THEN 'SIM' ELSE 'NÃO' END) AS "PEDIDO SISTEMA"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PF.CODCLI FROM PEDIDO_SIS PF WHERE PF.CODCLI = CLI.CODCLI) THEN 'SIM' ELSE 'NÃO' END) AS "DN"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 17528) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "DN"
FROM 
    PONTUAL.PCCLIENT CLI
JOIN
    ROTA R ON R.CODUSUR = CLI.CODUSUR1
JOIN
    PEDIDO_POSIT PP ON PP.CODUSUR = CLI.CODUSUR1
WHERE
    CODUSUR1 = 140    
