WITH ROTA AS (
    SELECT 
        CODUSUR,
        DIASEMANA,
        CODCLI,
        PERIODICIDADE,
        DTPROXVISITA,
        NUMSEMANA,
        DTFINAL,
        DTINICIO,
        CODCOMPROMISSO,
        DIAFIXO
    FROM 
        PONTUAL.PCROTACLI 
),

PEDIDO_POSIT AS (
    SELECT 
        DISTINCT(CODCLI),
        CODUSUR,
        NUMPED,
        CODPROD
    FROM 
        PONTUAL.PCPEDI
    WHERE
        DATA BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(SYSDATE)
    AND
        CODPROD IN (17528, 18157, 17484, 17506, 17462, 17507, 17517, 18446, 18035, 17932, 18079, 18448, 18447)
),

PEDIDO_SIS AS (
    SELECT 
        DISTINCT(NUMPED),
        CODUSUR,
        CODCLI
    FROM 
        PONTUAL.PCPEDI
    WHERE
        DATA BETWEEN TRUNC(SYSDATE, 'IW') AND TRUNC(SYSDATE, 'IW') + 6  -- TRUNC(SYSDATE, 'IW') retorna o primeiro dia da semana
),

PEDIDO_FAT AS (
    SELECT 
        DISTINCT(NUMPED),
        CODUSUR,
        CODCLI
    FROM 
        PONTUAL.PCPEDC
    WHERE
        DATA BETWEEN TRUNC(SYSDATE, 'IW') AND TRUNC(SYSDATE, 'IW') + 6  -- TRUNC(SYSDATE, 'IW') retorna o primeiro dia da semana
    AND
        POSICAO LIKE 'F'
)

SELECT
    DISTINCT(CLI.CODCLI)
    ,CLI.CLIENTE
    ,CLI.ENDERENT ||', ' || CLI.NUMEROENT AS "ENDEREÇO"
    ,CLI.BAIRROENT AS BAIRRO
    ,B.NOMECIDADE CIDADE
    ,(CASE WHEN CLI.CODCLI IN (SELECT PS.CODCLI FROM PEDIDO_SIS PS WHERE PS.CODCLI = CLI.CODCLI) THEN 'SIM' ELSE 'NÃO' END) AS "PEDIDO"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PF.CODCLI FROM PEDIDO_FAT PF WHERE PF.CODCLI = CLI.CODCLI) THEN 'SIM' ELSE 'NÃO' END) AS "DN"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 17528) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "17528"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 18157) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "18157"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 17484) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "17484"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 17506) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "17506"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 17462) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "17462"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 17507) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "17507"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 17517) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "17517"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD IN (18446, 18447)) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "18446 - 18447"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 18035) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "18035"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 17885) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "17885"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 17932) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "17932"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 18079) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "18079"
    ,(CASE WHEN CLI.CODCLI IN (SELECT PP.CODCLI FROM PEDIDO_POSIT PP WHERE PP.CODPROD = 18079) THEN (SELECT UNISTR('\2191')||UNISTR('\2191')||UNISTR('\2191') AS up_arrow FROM dual) ELSE (SELECT UNISTR('\2193')||UNISTR('\2193')||UNISTR('\2193') AS down_arrow FROM dual) END) AS "18448"
FROM 
    PONTUAL.PCCLIENT CLI
JOIN
    ROTA R ON R.CODCLI = CLI.CODCLI
JOIN 
    PCCIDADE B ON CLI.CODCIDADE = B.CODCIDADE    
WHERE
    CLI.CODUSUR1 = 141
AND
    R.NUMSEMANA = TO_NUMBER(TO_CHAR(SYSDATE, 'D'))