SELECT 
    A.CODCLI, 
    A.CLIENTE, 
    A.FANTASIA, 
    A.CGCENT, 
    A.TELENT, 
    A.FAXCLI, 
    A.TELCOB, 
    A.EMAIL, 
    B.NOMECIDADE,
    A.ENDERENT || ' ' || A.NUMEROENT || ' ' || A.BAIRROENT AS ENDEREÇO,
    A.ENDERCOB || ' ' || A.NUMEROCOB || ' ' || A.BAIRROCOB AS ENDEREÇO, 
    A.ENDERCOM || ' ' || A.NUMEROCOM || ' ' || A.BAIRROCOM AS ENDEREÇO
FROM 
    PCCLIENT A
JOIN 
    PCCIDADE B ON A.CODCIDADE = B.CODCIDADE
WHERE 
    A.CODCLI IN (SELECT DISTINCT(X.CODCLI) FROM PCMOV X JOIN PCPRODUT Y ON X.CODPROD = Y.CODPROD WHERE Y.CODFORNEC = 1634)
ORDER BY 
    CODCLI
