SELECT 
    CID.CIDADE, 
    A.CODPROD, 
    P.DESCRICAO, 
     SUM(A.QT) QTD,
    SUM(A.QT) * SUM(A.PVENDA) SUBTOTAL
FROM 
    PCPEDI A
LEFT JOIN 
    PCPRODUT P ON P.CODPROD = A.CODPROD
LEFT JOIN 
    (
        SELECT 
            CLI.CODCLI, 
            CLI.CODCIDADE || ' ' || CI.NOMECIDADE AS CIDADE
        FROM 
            PCCLIENT CLI 
        JOIN 
            PCCIDADE CI ON CI.CODCIDADE = CLI.CODCIDADE
    ) CID ON CID.CODCLI = A.CODCLI
WHERE 
    A.CODPROD IN (SELECT CODPROD FROM PCPRODUT WHERE CODFORNEC = 1488) 
    AND A.DATA > DATE '2024-01-01'
GROUP BY 
    CID.CIDADE, 
    A.CODPROD, 
    P.DESCRICAO
ORDER BY
    CIDADE, DESCRICAO;

