-- Com base na rotina 589

SELECT COUNT(*) AS QTDIASVENDAS 
FROM PCDIASUTEIS
WHERE CODFILIAL = 3
AND DIAVENDAS = 'S'
AND TO_CHAR(DATA, 'MM') = TO_CHAR(TO_DATE('01/03/2024', 'DD/MM/YYYY'), 'MM')
AND TO_CHAR(DATA, 'YYYY') = TO_CHAR(TO_DATE('01/03/2024', 'DD/MM/YYYY'), 'YYYY')