WITH CLIENTE AS(
    SELECT 
        A.CODCLI,
        A.CODUSUR
        
    FROM 
        PONTUAL.PCPEDI A
    WHERE
        A.CODPROD IN (SELECT CODPROD FROM PONTUAL.PCPRODUT WHERE CODFORNEC = 1719)
    AND
        A.DATA BETWEEN '01-AUG-2024' AND '31-AUG-2024'
    AND
        A.VLBONIFIC = 0

    GROUP BY
        A.CODCLI, 
        A.CODUSUR
    HAVING
        COUNT(DISTINCT A.CODPROD) >= 3
)

SELECT  
    USUR.CODUSUR COD,
    SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) AS RCA, -- EXTRAI O NOME
    COUNT(DISTINCT(C.CODCLI)) AS "DN",
    COUNT(DISTINCT(C.CODCLI)) * 5 AS "R$",
    usur.codsupervisor AS SUP

FROM 
    PONTUAL.PCUSUARI USUR
left JOIN 
    CLIENTE C ON USUR.CODUSUR = C.CODUSUR
    
GROUP BY 
    USUR.CODUSUR, 
    USUR.NOME,
    usur.codsupervisor
HAVING 
    USUR.NOME LIKE 'PMU%' 
AND 
    USUR.CODUSUR NOT IN (2, 160, 10)

ORDER BY DN DESC, cod asc