-------------------------------------------------------------------------------------------------------------------
WITH
    INAD AS 
    (
        SELECT DISTINCT(A.CODCLI)
        from pontual.pcprest A
        join pontual.pcclient B on A.codcli = B.codcli
        where A.dtvenc between SYSDATE-732 and SYSDATE-3
        and A.vpago is NULL
        and A.codcob in ('7563','SERA','C','CHD1')
    ),
-------------------------------------------------------------------------------------------------------------------
    F AS
    (SELECT M.CODCLI, SUM(M.QT) AS QTD
    FROM PONTUAL.PCMOV M
    WHERE M.CODPROD IN (18662, 18772, 18771, 18774, 18663, 18664, 18773)
    AND M.CODCLI IS NOT NULL
    AND M.CODOPER = 'SR'
    AND M.DTCANCEL IS NULL
    AND M.DTMOV BETWEEN DATE '2023-11-01' AND SYSDATE
    GROUP BY M.CODCLI
    ORDER BY QTD ASC),
-------------------------------------------------------------------------------------------------------------------
    DF AS
    (SELECT M.CODCLI, SUM(M.QT) AS QTD
    FROM PONTUAL.PCMOV M
    WHERE M.CODPROD IN (18662, 18772, 18771, 18774, 18663, 18664, 18773)
    AND M.CODCLI IS NOT NULL
    AND M.CODOPER = 'ER'
    AND M.DTCANCEL IS NULL
    AND M.DTMOV BETWEEN DATE '2023-11-01' AND SYSDATE
    GROUP BY M.CODCLI
    ORDER BY QTD ASC)
-------------------------------------------------------------------------------------------------------------------

SELECT AUX.CODCLI || ' - ' || SUBSTR(AUX.CLIENTE,0,25) AS CLIENTE,
        SUBSTR(AUX.FANTASIA,0,30) FANTASIA, 
        aux.BLOQUEIO, 
       (CASE WHEN AUX.CODCLI IN (SELECT X.CODCLI FROM INAD X) THEN 'S' ELSE 'N' END) AS "INAD.",
       NVL((SELECT F.QTD - DF.QTD FROM F, DF WHERE F.CODCLI = AUX.CODCLI AND DF.CODCLI = AUX.CODCLI),0) AS "QTD FREEZER",
       AUX.DTULTCOMP, 
       AUX.DTCADASTRO, 
       AUX.DTPRIMCOMPRA, 
       AUX.CODUSUR1 CODUSUR, 
       AUX.NOME, 
       AUX.SUPERVISOR
FROM (
SELECT DISTINCT PCCLIENT.CODCLI, PCCLIENT.CLIENTE, PCCLIENT.FANTASIA,
       (SELECT MAX(PCPEDC.DATA)
        FROM PONTUAL.PCPEDC, PONTUAL.PCPEDI, PONTUAL.PCPRODUT
         WHERE PCPEDC.CODCLI = PCCLIENT.CODCLI
           AND PCPEDC.NUMPED = PCPEDI.NUMPED
           AND PCPRODUT.CODPROD = PCPEDI.CODPROD
AND PCPRODUT.CODFORNEC IN ('1841')
 AND PCPRODUT.CODSEC IN ('120427','1005','11006','120387','10040','10042','120239','120424','10047','10046','10048','1033','120423','11007','10043','10041','10044','120430','1003','10001','1023','10050','120432')
           AND PCPEDC.CODFILIAL IN ('3')
           AND PCPEDC.POSICAO IN('L', 'M', 'F', 'P', 'B')
           AND PCPEDC.DTCANCEL IS NULL)
DTULTCOMP,
PCCLIENT.CODUSUR1, 
(CASE WHEN PCCLIENT.CODUSUR1 IN (10,50) THEN 'INTERNO' ELSE
 (SELECT SUBSTR(PCUSUARI.nome, INSTR(PCUSUARI.nome, ' ') + 1, INSTR(PCUSUARI.nome, ' ', INSTR(PCUSUARI.nome, ' ') + 1) - INSTR(PCUSUARI.nome, ' ') - 1) FROM PONTUAL.PCUSUARI WHERE PCUSUARI.CODUSUR = PCCLIENT.CODUSUR1)
 END) AS nome,
SUBSTR(PCSUPERV.NOME, INSTR(PCSUPERV.NOME, ' ') + 1, INSTR(PCSUPERV.NOME, ' ', INSTR(PCSUPERV.NOME, ' ') + 1) - INSTR(PCSUPERV.NOME, ' ') - 1) AS SUPERVISOR,
PCCLIENT.DTPRIMCOMPRA, PCCLIENT.DTCADASTRO, PCCLIENT.BLOQUEIO
FROM PONTUAL.PCCLIENT, PONTUAL.PCUSUARI, PONTUAL.PCSUPERV, PONTUAL.PCPRACA
WHERE 1 = 1
 AND PCUSUARI.CODSUPERVISOR IN ('8')
 AND PCCLIENT.CODCLI NOT IN
       (SELECT PCPEDC.CODCLI
          FROM PONTUAL.PCPEDC, PONTUAL.PCPEDI, PONTUAL.PCPRODUT
         WHERE PCPEDC.NUMPED = PCPEDI.NUMPED
           AND PCPRODUT.CODPROD = PCPEDI.CODPROD
           AND PCPEDC.DTCANCEL IS NULL
AND PCPRODUT.CODFORNEC IN ('1841')
 AND PCPRODUT.CODSEC IN ('120427','1005','11006','120387','10040','10042','120239','120424','10047','10046','10048','1033','120423','11007','10043','10041','10044','120430','1003','10001','1023','10050','120432')
   AND ((trunc(sysdate) - pcpedc.data) <= 30)
                 AND PCPEDC.CODFILIAL IN ('3')
           AND PCPEDC.DTCANCEL IS NULL
 )
 AND (PCUSUARI.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR) 
 AND (PCCLIENT.CODPRACA = PCPRACA.CODPRACA)            
AND (((PCCLIENT.CODUSUR1 = PCUSUARI.CODUSUR) OR
    (PCCLIENT.CODUSUR2 = PCUSUARI.CODUSUR)) OR
  EXISTS (SELECT CODCLI FROM PONTUAL.PCUSURCLI WHERE PCUSURCLI.CODCLI = PCCLIENT.CODCLI AND PCUSURCLI.CODUSUR = PCUSUARI.CODUSUR))
) AUX
