-------------------------------------------------------------------------------------------------------------------
WITH
    INAD AS 
    (
        SELECT DISTINCT(A.CODCLI)
        FROM PONTUAL.PCPREST A
        JOIN PONTUAL.PCCLIENT B ON A.CODCLI = B.CODCLI
        WHERE A.DTVENC BETWEEN SYSDATE-732 AND SYSDATE-3
        AND A.VPAGO IS NULL
        AND A.CODCOB IN ('7563','SERA','C','CHD1')
    ),
-------------------------------------------------------------------------------------------------------------------
    F AS
    (SELECT M.CODCLI, SUM(M.QT) AS QTD
    FROM PONTUAL.PCMOV M
    WHERE M.CODPROD IN (18662, 18772, 18771, 18774, 18663, 18664, 18773)
    AND M.CODCLI IS NOT NULL
    AND M.CODOPER = 'SR'
    AND M.DTCANCEL IS NULL
    AND M.DTMOV BETWEEN DATE '2023-11-01' AND SYSDATE
    GROUP BY M.CODCLI
    ORDER BY QTD ASC),
-------------------------------------------------------------------------------------------------------------------
    DF AS
    (SELECT M.CODCLI, SUM(M.QT) AS QTD
    FROM PONTUAL.PCMOV M
    WHERE M.CODPROD IN (18662, 18772, 18771, 18774, 18663, 18664, 18773)
    AND M.CODCLI IS NOT NULL
    AND M.CODOPER = 'ER'
    AND M.DTCANCEL IS NULL
    AND M.DTMOV BETWEEN DATE '2023-11-01' AND SYSDATE
    GROUP BY M.CODCLI
    ORDER BY QTD ASC)
-------------------------------------------------------------------------------------------------------------------

SELECT DISTINCT(AUX.CODCLI) || ' - ' || SUBSTR(AUX.CLIENTE,0,25) AS CLIENTE,
       AUX.CODUSUR1 CODUSUR, 
       AUX.NOME, 
       AUX.SUPERVISOR,
       SUBSTR(AUX.FANTASIA,0,30) FANTASIA, 
       AUX.DTULTCOMP, 
       AUX.BLOQUEIO, 
       (CASE WHEN AUX.CODCLI IN (SELECT X.CODCLI FROM INAD X) THEN 'S' ELSE 'N' END) AS "INAD.",
       NVL((SELECT F.QTD - DF.QTD FROM F, DF WHERE F.CODCLI = AUX.CODCLI AND DF.CODCLI = AUX.CODCLI),0) AS "FREEZER",

       AUX.DTCADASTRO, 
       AUX.DTPRIMCOMPRA
FROM (
SELECT DISTINCT PCCLIENT.CODCLI, PCCLIENT.CLIENTE, PCCLIENT.FANTASIA,
       (SELECT MAX(PCPEDC.DATA)
        FROM PONTUAL.PCPEDC, PONTUAL.PCPEDI, PONTUAL.PCPRODUT
         WHERE PCPEDC.CODCLI = PCCLIENT.CODCLI
           AND PCPEDC.NUMPED = PCPEDI.NUMPED
           AND PCPRODUT.CODPROD = PCPEDI.CODPROD
AND PCPRODUT.CODFORNEC IN ('{fornec}')
 AND PCPRODUT.CODSEC IN ('120427','1005','11006','120387','10040','10042','120239','120424','10047','10046','10048','1033','120423','11007','10043','10041','10044','120430','1003','10001','1023','10050','120432')
           AND PCPEDC.CODFILIAL IN ('3')
           AND PCPEDC.POSICAO IN('L', 'M', 'F', 'P', 'B')
           AND PCPEDC.DTCANCEL IS NULL)
DTULTCOMP,
PCCLIENT.CODUSUR1, 
(CASE WHEN PCCLIENT.CODUSUR1 IN (10,50) THEN 'INTERNO' ELSE
 (SELECT SUBSTR(PCUSUARI.NOME, INSTR(PCUSUARI.NOME, ' ') + 1, INSTR(PCUSUARI.NOME, ' ', INSTR(PCUSUARI.NOME, ' ') + 1) - INSTR(PCUSUARI.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI WHERE PCUSUARI.CODUSUR = PCCLIENT.CODUSUR1)
 END) AS NOME,
(SELECT SUBSTR(P.NOME, INSTR(P.NOME, ' ') + 1, INSTR(P.NOME, ' ', INSTR(P.NOME, ' ') + 1) - INSTR(P.NOME, ' ') - 1) FROM PONTUAL.PCSUPERV P WHERE PCUSUARI.codsupervisor = P.codsupervisor) AS SUPERVISOR,
PCCLIENT.DTPRIMCOMPRA, PCCLIENT.DTCADASTRO, PCCLIENT.BLOQUEIO
FROM PONTUAL.PCCLIENT, PONTUAL.PCUSUARI, PONTUAL.PCSUPERV
WHERE 1 = 1
 AND PCUSUARI.CODSUPERVISOR {supOnOff} ({sup})
 AND PCCLIENT.CODCLI NOT IN
       (SELECT PCPEDC.CODCLI
          FROM PONTUAL.PCPEDC, PONTUAL.PCPEDI, PONTUAL.PCPRODUT
         WHERE PCPEDC.NUMPED = PCPEDI.NUMPED
           AND PCPRODUT.CODPROD = PCPEDI.CODPROD
           AND PCPEDC.DTCANCEL IS NULL
AND PCPRODUT.CODFORNEC IN ('{fornec}')
 AND PCPRODUT.CODSEC IN ('120427','1005','11006','120387','10040','10042','120239','120424','10047','10046','10048','1033','120423','11007','10043','10041','10044','120430','1003','10001','1023','10050','120432')
   AND ((TRUNC(SYSDATE) - PCPEDC.DATA) <= 30)
                 AND PCPEDC.CODFILIAL IN ('3')
           AND PCPEDC.DTCANCEL IS NULL
 )
 AND (PCUSUARI.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR)     
AND (((PCCLIENT.CODUSUR1 = PCUSUARI.CODUSUR)))
) AUX
WHERE AUX.CODUSUR1 {rcaOnOff} ({rca})
ORDER BY "FREEZER" DESC, DTULTCOMP ASC