-- Com base na rotina 589

SELECT COUNT(*) AS QTDIASVENDAS 
FROM PONTUAL.PCDIASUTEIS
WHERE CODFILIAL = 3
AND DIAVENDAS = 'S'
AND TO_CHAR(DATA, 'MM') = TO_CHAR(SYSDATE, 'MM')
AND TO_CHAR(DATA, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')