WITH DIADECORRIDO AS (
    SELECT DATA, 
        CASE WHEN DATA <= SYSDATE-1 THEN 'D' ELSE 'F' END AS DIADECORRIDO
    FROM PONTUAL.PCDIASUTEIS
    WHERE CODFILIAL = 3
    AND DIAVENDAS = 'S'
    AND TO_CHAR(DATA, 'MM') = TO_CHAR(SYSDATE, 'MM')
    AND TO_CHAR(DATA, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')
)

SELECT COUNT(DIADECORRIDO)
FROM DIADECORRIDO
WHERE DIADECORRIDO = 'D'