WITH DIASDECORRIDOS AS (
    SELECT DATA, 
        CASE WHEN DATA <= SYSDATE-1 THEN 'D' ELSE 'F' END AS DIASDECORRIDOS
    FROM PONTUAL.PCDIASUTEIS
    WHERE CODFILIAL = 3
    AND DIAVENDAS = 'S'
    AND TO_CHAR(DATA, 'MM') = TO_CHAR(SYSDATE, 'MM')
    AND TO_CHAR(DATA, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')
)

SELECT COUNT(DIASDECORRIDOS)
FROM DIASDECORRIDOS
WHERE DIASDECORRIDOS = 'D'