WITH DN_TOTAL as (   --TOTAL
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODFORNEC = {fornec}
            AND PED.CODUSUR = {rca}
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

QTD_CLI AS (
        /* SQL UTILIZADO PELA ROTINA PCSIS322 RELATORIO(S) - 22 */ 
        SELECT COUNT(DISTINCT(PCCLIENT.CODCLI)) QTCLIATIVOS, PCUSUARI.CODUSUR AS RCA FROM PONTUAL.PCCLIENT, PONTUAL.PCUSUARI
        WHERE ((PCCLIENT.CODUSUR1 = PCUSUARI.CODUSUR) OR (PCCLIENT.CODUSUR2 = PCUSUARI.CODUSUR) OR 
                 EXISTS (SELECT PCUSURCLI.CODUSUR
                           FROM PONTUAL.PCUSURCLI
                          WHERE PCUSURCLI.CODUSUR = PCUSUARI.CODUSUR
                            AND PCUSURCLI.CODCLI  = PCCLIENT.CODCLI))
        AND ( PCCLIENT.DTULTCOMP >= trunc(sysdate - 90) )
        AND (PCUSUARI.CODFILIAL IN ('3') OR (NVL(PCUSUARI.CODFILIAL,'99') = '99' ))
        AND PCCLIENT.DTEXCLUSAO IS NULL
               and (PCUSUARI.CODSUPERVISOR in (2,8)) 
           GROUP BY PCUSUARI.CODUSUR),

       ---------------------------------------------------------------   

META AS (
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS META
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(TRUNC(SYSDATE, 'MM') - 90) and TRUNC(SYSDATE, 'MM')
            AND PROD.CODFORNEC = {fornec}
            AND PED.CODUSUR = {rca}
            AND PED.DTCANCEL IS NULL
            AND PED.POSICAO = 'F'
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR)

--------------------------------------------------------------------------------------------------------------------
SELECT NVL(META.META, 0) AS OBJETIVO, 
    NVL(DN_TOTAL.DN, 0) AS REALIZADO, 
    GREATEST(NVL(META.META, 0) - NVL(DN_TOTAL.DN, 0), 0) AS "R.A.F.",
    (NVL(DN_TOTAL.DN, 1) / NVL(META.META, 1)) AS "% ATINGIDO"
FROM   DN_TOTAL
JOIN   META ON DN_TOTAL.RCA = META.RCA
JOIN   QTD_CLI ON DN_TOTAL.RCA = QTD_CLI.RCA
