WITH DN_PLF As ( --IOGURTE DANONE
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (10040,10042,120239) -- PLF          
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_DNE As ( --DANONE
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODFORNEC in (588) -- TODAS SEÇÕES DANONE       
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_ACT As ( --ACTIVIA DANONE
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (10040) -- ACTIVIA       
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_DNH As ( --DANONINHO DANONE
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (10042) -- DANONINHO      
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_GRA As ( --GRANADA DANONE
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (120239) -- GRANADA     
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_UHT As ( --UHT DANONE
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (10046) --UHT     
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_REQ As ( --REQUEIJAO DANONE
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (10047) --REQUEIJAO    
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_YOP As ( --YOPRO DANONE
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (10048) -- YOPRO   
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_SUL as ( --SULMINAS
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (10050) -- SULMINAS
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_FIN as ( --FINI
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (11007) -- FINI
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_GUL as ( --GULOZITOS
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (10044) -- GULOZITOS
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_ECO as ( --ECOFRESH
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (120427) -- ECOFRESH
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_DFT as (  --DAFRUTA
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (120387) -- DAFRUTA
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_DNL as (   --DANILLA
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (120424)  --DANILLA
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_SEA as (   -- SEARA MASSA LEVE
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (10001) -- SEARA MASSA LEVE
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_HYT as (   -- HYTS
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC  in (1005) -- HYTS
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_STM as (  -- SANTA MASSA
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC  in (1023) -- SANTA MASSA
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_FTP as (  -- FRUTAP
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (10041) -- FRUTAP
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_MGN as (  --MARGARINA
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (1003) --MARGARINA
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

WITH DN_TOTAL as (   --TOTAL
        SELECT PED.CODUSUR AS RCA,
            COUNT(DISTINCT PED.CODCLI) AS DN
        FROM PONTUAL.PCPEDC PED
            JOIN PONTUAL.PCPEDI PEDI ON PEDI.NUMPED = PED.NUMPED
            JOIN PONTUAL.PCPRODUT PROD ON PEDI.CODPROD = PROD.CODPROD
        WHERE PED.DATA BETWEEN TRUNC(SYSDATE, 'MM') and LAST_DAY(SYSDATE)
            AND PROD.CODSEC in (10041,1023,1005,10001,120424,120387,120427,10044,11007,10046,10047,120239,10048,10042,1003,10040)
            AND PED.DTCANCEL IS NULL
            AND PED.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
        GROUP BY PED.CODUSUR),

       ---------------------------------------------------------------   

QTD_CLI AS (
        /* SQL UTILIZADO PELA ROTINA PCSIS322 RELATORIO(S) - 22 */ 
        SELECT COUNT(DISTINCT(PCCLIENT.CODCLI)) QTCLIATIVOS, PCUSUARI.CODUSUR FROM PCCLIENT, PCUSUARI
        WHERE ((PCCLIENT.CODUSUR1 = PCUSUARI.CODUSUR) OR (PCCLIENT.CODUSUR2 = PCUSUARI.CODUSUR) OR 
                 EXISTS (SELECT PCUSURCLI.CODUSUR
                           FROM PCUSURCLI
                          WHERE PCUSURCLI.CODUSUR = PCUSUARI.CODUSUR
                            AND PCUSURCLI.CODCLI  = PCCLIENT.CODCLI))
        AND ( PCCLIENT.DTULTCOMP >= trunc(sysdate - 90) )
        AND (PCUSUARI.CODFILIAL IN ('3') OR (NVL(PCUSUARI.CODFILIAL,'99') = '99' ))
        AND PCCLIENT.DTEXCLUSAO IS NULL
               and (PCUSUARI.CODSUPERVISOR in (2,8)) 
           GROUP BY PCUSUARI.CODUSUR)

--------------------------------------------------------------------------------------------------------------------
