SELECT 
    SUP.codsupervisor,
    (SELECT SUBSTR(PCUSUARI.NOME, INSTR(PCUSUARI.NOME, ' ') + 1, INSTR(PCUSUARI.NOME, ' ', INSTR(PCUSUARI.NOME, ' ') + 1) - INSTR(PCUSUARI.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI WHERE PCUSUARI.CODUSUR = SUP.COD_CADRCA) AS NOME,
    SUP.NOME "NOME COMPLETO",
    COD_CADRCA

FROM 
    PONTUAL.PCSUPERV SUP
WHERE 
    SUP.NOME LIKE 'PMU %'
AND 
    SUP.POSICAO = 'A'
    
ORDER BY
    1 ASC