SELECT 
    P.CODUSUR CODSUR,
    (SELECT SUBSTR(PCUSUARI.NOME, INSTR(PCUSUARI.NOME, ' ') + 1, INSTR(PCUSUARI.NOME, ' ', INSTR(PCUSUARI.NOME, ' ') + 1) - INSTR(PCUSUARI.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI WHERE PCUSUARI.CODUSUR = P.CODUSUR) AS NOME,
    P.NOME NOME_COMPLETO,
    P.CODSUPERVISOR

FROM 
    PONTUAL.PCUSUARI P
WHERE 
    P.NOME LIKE 'PMU %'
AND 
    P.BLOQUEIO = 'N'
    
ORDER BY
    1 ASC