SELECT DISTINCT
    F.CODFORNEC,
    F.FANTASIA,
    F.FORNECEDOR

FROM
    PONTUAL.PCFORNEC F
JOIN
    PONTUAL.PCPRODUT P ON F.CODFORNEC = P.CODFORNEC
JOIN
    PONTUAL.PCPEDI D ON P.CODPROD = D.CODPROD
WHERE
    D.DATA BETWEEN SYSDATE - 32 AND SYSDATE