SELECT
    PED.CODCLI || '' AS CLIENTE,
    PEDC.CODUSUR AS RCA,
    (SELECT SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI USUR WHERE USUR.CODUSUR = PEDC.CODUSUR) AS NOME,
    'POSSÍVEL DUPLICIDADE' AS TIPO,
    NULL AS STATUS
FROM
    PONTUAL.PCPEDI PED
JOIN
    PONTUAL.PCPEDC PEDC ON PED.CODCLI = PEDC.CODCLI
AND PED.NUMPED = PEDC.NUMPED
AND PED.DATA = PEDC.DATA
LEFT JOIN
    (
    SELECT
        PED2.CODCLI,
        PED2.CODPROD
    FROM
        PONTUAL.PCPEDI PED2
    JOIN
        PONTUAL.PCPEDC PEDC2 ON PED2.NUMPED = PEDC2.NUMPED
    WHERE
        PED2.DATA BETWEEN SYSDATE-7 AND SYSDATE
    AND PED2.POSICAO NOT IN ('F', 'C')
    AND PEDC2.CONDVENDA NOT IN (5, 11)
    GROUP BY
        PED2.CODCLI,
        PED2.CODPROD
    HAVING COUNT(*) > 1
    ) PED2 ON PED.CODCLI = PED2.CODCLI 
WHERE
    PED.DATA BETWEEN SYSDATE-7 AND SYSDATE
AND PED.POSICAO NOT IN ('F', 'C')
AND PEDC.CONDVENDA NOT IN (5, 11)
AND PED2.CODCLI IS NOT NULL
GROUP BY
    PED.CODCLI,
    PEDC.CODUSUR
------------------------------------------------------------------------------------------------------------------
UNION ALL
SELECT DISTINCT
    A.CODCLI || '' AS CLIENTE,
    PEDC.CODUSUR AS RCA,
    (SELECT SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI USUR WHERE USUR.CODUSUR = A.CODUSUR) AS NOME,
    'BNF SEM PEDIDO' AS TIPO,
    (CASE
        WHEN PEDC.POSICAO LIKE 'B' THEN PEDC.POSICAO || 'LOQUEADO' 
        WHEN PEDC.POSICAO LIKE 'C' THEN PEDC.POSICAO || 'ANCELADO'
        WHEN PEDC.POSICAO LIKE 'P' THEN PEDC.POSICAO || 'ENDENTE'
        WHEN PEDC.POSICAO LIKE 'M' THEN PEDC.POSICAO || 'ONTADO'
        ELSE PEDC.POSICAO || 'IBERADO'
        END) AS STATUS
FROM PONTUAL.PCPEDC A
JOIN PONTUAL.PCPEDC PEDC ON PEDC.CODCLI = A.CODCLI AND PEDC.NUMPED = A.NUMPED AND PEDC.DATA = A.DATA
WHERE A.DATA BETWEEN SYSDATE-7 AND SYSDATE
AND A.CONDVENDA IN (5,11)
AND A.POSICAO != 'F' AND A.POSICAO != 'C'
AND NOT EXISTS (
    SELECT 1 FROM PONTUAL.PCPEDC B
    WHERE B.DATA BETWEEN SYSDATE-7 AND SYSDATE
    AND B.CONDVENDA = 1
    AND A.CODCLI = B.CODCLI
    AND A.POSICAO != 'F' AND A.POSICAO != 'C'
)
AND A.CODCLI != 11185 --PREMIUM
------------------------------------------------------------------------------------------------------------------
UNION ALL
SELECT DISTINCT
    A.CODCLI || '' AS CLIENTE,
    A.CODUSUR1 AS RCA,
    (SELECT SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI USUR WHERE USUR.CODUSUR = A.CODUSUR1) AS NOME,
    'ERRO CADASTRO (UF)' AS TIPO,
    NULL AS STATUS
FROM PONTUAL.PCCLIENT A
WHERE A.ESTENT LIKE '' OR A.ESTENT IS NULL
------------------------------------------------------------------------------------------------------------------
UNION ALL
SELECT DISTINCT
    A.CODCLI || '' AS CLIENTE,
    A.CODUSUR AS RCA,
    (SELECT SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI USUR WHERE USUR.CODUSUR = A.CODUSUR) AS NOME,
    'PEDIDO ABAIXO DO MÍNIMO' AS TIPO,
    (CASE
        WHEN A.POSICAO LIKE 'B' THEN A.POSICAO || 'LOQUEADO' 
        WHEN A.POSICAO LIKE 'C' THEN A.POSICAO || 'ANCELADO'
        WHEN A.POSICAO LIKE 'P' THEN A.POSICAO || 'ENDENTE'
        WHEN A.POSICAO LIKE 'M' THEN A.POSICAO || 'ONTADO'
        ELSE A.POSICAO || 'IBERADO'
        END) AS STATUS
FROM PONTUAL.PCPEDC A
WHERE A.DATA > SYSDATE-6
AND A.CONDVENDA IN (1)
AND A.POSICAO != 'F' AND A.POSICAO != 'C' AND A.POSICAO != 'M'
AND A.VLATEND < 100
------------------------------------------------------------------------------------------------------------------
UNION ALL
SELECT DISTINCT
    C.CODCLI || '' AS CLIENTE,
    C.CODUSUR AS RCA,
    (SELECT SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI USUR WHERE USUR.CODUSUR = C.CODUSUR) AS NOME,
    'ERRO DE PRAZO NO BOLETO' || C.CODPLPAG AS TIPO,
    (CASE
        WHEN C.POSICAO LIKE 'B' THEN C.POSICAO || 'LOQUEADO' 
        WHEN C.POSICAO LIKE 'C' THEN C.POSICAO || 'ANCELADO'
        WHEN C.POSICAO LIKE 'P' THEN C.POSICAO || 'ENDENTE'
        WHEN C.POSICAO LIKE 'M' THEN C.POSICAO || 'ONTADO'
        ELSE C.POSICAO || 'IBERADO'
        END) AS STATUS 
FROM PONTUAL.PCPEDC C 
WHERE C.CODCOB IN ('7563') 
AND C.CODPLPAG NOT IN (3,4,5,6,10,12,17,21,28,29,38,39,40,41,43,44,45,46,47,70)
AND C.POSICAO NOT IN ('F', 'C')
AND C.DATA > SYSDATE-6
------------------------------------------------------------------------------------------------------------------
UNION ALL
SELECT DISTINCT
    C.CODCLI || '' AS CLIENTE,
    C.CODUSUR AS RCA,
    (SELECT SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI USUR WHERE USUR.CODUSUR = C.CODUSUR) AS NOME,
    'ERRO DE PLPAG NA BNF' AS TIPO,
    (CASE
        WHEN C.POSICAO LIKE 'B' THEN C.POSICAO || 'LOQUEADO' 
        WHEN C.POSICAO LIKE 'C' THEN C.POSICAO || 'ANCELADO'
        WHEN C.POSICAO LIKE 'P' THEN C.POSICAO || 'ENDENTE'
        WHEN C.POSICAO LIKE 'M' THEN C.POSICAO || 'ONTADO'
        ELSE C.POSICAO || 'IBERADO'
        END) AS STATUS 
FROM PONTUAL.PCPEDC C 
WHERE C.CODCOB IN ('BNF','BNFT','BNFP') 
AND C.CODPLPAG NOT IN (8)
AND C.POSICAO NOT IN ('F', 'C')
------------------------------------------------------------------------------------------------------------------
UNION ALL
SELECT 
    LIBERADOS.CLIENTE || '',
    LIBERADOS.RCA,
    (SELECT SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI USUR WHERE USUR.CODUSUR = LIBERADOS.RCA) AS NOME,
    LIBERADOS.CONTAGEM || ' LIBERADO(S), ' || NVL(BLOQUEADOS.CONTAGEM, 0) || ' BLOQUEADO(S)' AS TIPO,
    '' AS STATUS
FROM
    (SELECT 
        C.CODCLI AS CLIENTE,
        C.CODUSUR AS RCA,
        COUNT(DISTINCT C.NUMPED) AS CONTAGEM
    FROM
        PONTUAL.PCPEDC C 
    WHERE
        C.DATA BETWEEN SYSDATE-7 AND SYSDATE
    AND 
        C.POSICAO = 'L' --LIBERADO
    GROUP BY 
        C.CODCLI, 
        C.CODUSUR) LIBERADOS
LEFT JOIN
    (SELECT 
        B.CODCLI AS CLIENTE,
        B.CODUSUR AS RCA,
        COUNT(DISTINCT B.NUMPED) AS CONTAGEM
    FROM
        PONTUAL.PCPEDC B 
    WHERE
        B.DATA BETWEEN SYSDATE-7 AND SYSDATE
    AND 
        B.POSICAO IN ('P', 'B') --PENDENTE OU BLOQUEADO
    GROUP BY 
        B.CODCLI, 
        B.CODUSUR) BLOQUEADOS
ON
    LIBERADOS.CLIENTE = BLOQUEADOS.CLIENTE --AND LIBERADOS.RCA = BLOQUEADOS.RCA
WHERE 
    BLOQUEADOS.CONTAGEM IS NOT NULL
AND (
        (TO_CHAR(SYSDATE, 'D') BETWEEN 2 AND 5 AND TO_CHAR(SYSDATE, 'HH24:MI') > '15:30')
        OR
        (TO_CHAR(SYSDATE, 'D') = 6 AND TO_CHAR(SYSDATE, 'HH24:MI') > '11:45')
        OR
        TO_CHAR(SYSDATE, 'D') = 7
    )    

------------------------------------------------------------------------------------------------------------------
UNION ALL
SELECT 
    P.CODCLI || '' AS CLIENTE,
    P.CODUSUR1 RCA,
    (SELECT SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI USUR WHERE USUR.CODUSUR = P.CODUSUR1) AS NOME,
    'ERRO CADASTRO (IE != ISENTO)' AS TIPO,
    NULL AS STATUS
FROM 
    PONTUAL.PCCLIENT P
WHERE 
    P.TIPOFJ = 'F'
AND
    P.IEENT NOT LIKE 'ISENTO'    
------------------------------------------------------------------------------------------------------------------
UNION ALL
SELECT 
    P.CODCLI || '' AS CLIENTE,
    P.CODUSUR1 RCA,
    (SELECT SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI USUR WHERE USUR.CODUSUR = P.CODUSUR1) AS NOME,
    'ERRO CADASTRO (CONTRIBUINTE)' AS TIPO,
    NULL AS STATUS
FROM 
    PONTUAL.PCCLIENT P
WHERE 
    P.TIPOFJ = 'F'
AND
    (P.CONTRIBUINTE NOT LIKE 'N')
AND
    (P.CODUSUR1 NOT IN (10, 2, 160, 50))
------------------------------------------------------------------------------------------------------------------
UNION ALL
SELECT 
    P.CODCLI || '' AS CLIENTE,
    P.CODUSUR1 RCA,
    (SELECT SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI USUR WHERE USUR.CODUSUR = P.CODUSUR1) AS NOME,
    'ERRO CADASTRO (CONSUMIDOR)' AS TIPO,
    NULL AS STATUS
FROM 
    PONTUAL.PCCLIENT P
WHERE 
    P.TIPOFJ = 'F'
AND
    (P.CONSUMIDORFINAL NOT LIKE 'S')
AND
    (P.CODUSUR1 NOT IN (10, 2, 160, 50))
------------------------------------------------------------------------------------------------------------------
UNION ALL
SELECT 
    P.CODCLI || '' AS CLIENTE,
    P.CODUSUR1 RCA,
    (SELECT SUBSTR(USUR.NOME, INSTR(USUR.NOME, ' ') + 1, INSTR(USUR.NOME, ' ', INSTR(USUR.NOME, ' ') + 1) - INSTR(USUR.NOME, ' ') - 1) FROM PONTUAL.PCUSUARI USUR WHERE USUR.CODUSUR = P.CODUSUR1) AS NOME,
    'ZERO A ESQUERDA NA IE' AS TIPO,
    NULL AS STATUS
FROM 
    PONTUAL.PCCLIENT P
WHERE 
    P.IEENT LIKE '0%'
AND
    P.DTEXCLUSAO IS NULL



----------------------------
ORDER BY 4, 3, 1
----------------------------