WITH VL AS (
SELECT A.CODUSUR, A.VLVENDA, B.VLBONIFIC
FROM
(/* SQL UTILIZADO PELA ROTINA PCSIS322 PARA TODOS OS RELATÓRIOS */
SELECT PCPEDC.CODUSUR,
       SUM(PCPEDI.QT) AS QT,
       SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2)) AS VLVENDA,
       SUM(ROUND(NVL(PCPRODUT.PESOBRUTO,0)*NVL(PCPEDI.QT,0),2)) AS TOTPESO,
       COUNT(DISTINCT(PCPEDC.CODCLI)) AS QTCLIPOS,
       SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.VLCUSTOFIN,0),2)) AS VLCUSTOFIN,
  ((SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2))
  -  SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.VLCUSTOFIN,0),2))) /  decode(SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.PVENDA,0),2)),0,1,SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.PVENDA,0),2))) * 100 ) as clPERLUC
FROM     
PONTUAL.PCPEDI,  
PONTUAL.PCPEDC,  
PONTUAL.PCPRODUT,
PONTUAL.PCCLIENT,
PONTUAL.PCFORNEC
WHERE 1=1 
AND PCPEDC.DATA BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(SYSDATE)
AND PCPEDI.DATA BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(SYSDATE)
AND PCPEDC.CODFILIAL IN ('3')
   AND (PCPEDC.CODUSUR IN ( {rca} )) 
AND PCPEDC.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
and PCPEDC.NUMPED    = PCPEDI.NUMPED
AND   PCPEDI.CODPROD   = PCPRODUT.CODPROD
AND   PCPEDC.CODCLI    = PCCLIENT.CODCLI
AND   PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
AND   PCPRODUT.CODSEC IN (10040,10042,120239)
 AND NVL(PCPEDI.BONIFIC, 'N') =  'N' 
AND   PCPEDC.DTCANCEL IS NULL
GROUP BY PCPEDC.CODUSUR
) A
JOIN (/* SQL UTILIZADO PELA ROTINA PCSIS322 PARA TODOS OS RELATÓRIOS */
SELECT PCPEDC.CODUSUR,
       SUM(PCPEDI.QT) AS QT,
       SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2)) AS VLBONIFIC,
       SUM(ROUND(NVL(PCPRODUT.PESOBRUTO,0)*NVL(PCPEDI.QT,0),2)) AS TOTPESO,
       COUNT(DISTINCT(PCPEDC.CODCLI)) AS QTCLIPOS,
       SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.VLCUSTOFIN,0),2)) AS VLCUSTOFIN,
  ((SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2))
  -  SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.VLCUSTOFIN,0),2))) /  decode(SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.PVENDA,0),2)),0,1,SUM(ROUND(NVL(PCPEDI.QT,0)*NVL(PCPEDI.PVENDA,0),2))) * 100 ) as clPERLUC
FROM     
PONTUAL.PCPEDI,  
PONTUAL.PCPEDC,  
PONTUAL.PCPRODUT,
PONTUAL.PCCLIENT,
PONTUAL.PCFORNEC
WHERE 1=1 
AND PCPEDC.DATA BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(SYSDATE)
AND PCPEDI.DATA BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(SYSDATE)
AND PCPEDC.CODFILIAL IN ('3')
   AND (PCPEDC.CODUSUR IN ( {rca} )) 
AND PCPEDC.CONDVENDA IN (5,11)
and PCPEDC.NUMPED    = PCPEDI.NUMPED
AND   PCPEDI.CODPROD   = PCPRODUT.CODPROD
AND   PCPEDC.CODCLI    = PCCLIENT.CODCLI
AND   PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
 AND NVL(PCPEDI.BONIFIC, 'N') =  'N' 
AND   PCPEDC.DTCANCEL IS NULL
GROUP BY PCPEDC.CODUSUR
) B ON A.CODUSUR = B.CODUSUR),

FLEX AS (
SELECT u.codusur, u.nome AS Nome, a.Verba AS GERADO
FROM PONTUAL.PCUSUARI u
JOIN (
    SELECT a.codusur as RCA, 
    SUM(CASE WHEN (a.ptabela - a.punit) < 0 THEN (a.ptabela - a.punit) * a.qt ELSE 0 END) AS Verba
    FROM PONTUAL.PCMOV a
    WHERE a.dtmov BETWEEN TRUNC(SYSDATE, 'MM') AND LAST_DAY(SYSDATE)
    AND a.codusur in (SELECT CODUSUR FROM PONTUAL.PCUSUARI WHERE NOME like 'PMU%')
    AND A.CODFORNEC IN (SELECT CODFORNEC FROM PONTUAL.PCFORNEC 
                        WHERE CODFORNEC IN (588, 1225, 1321, 1488, 1541, 1607, 1621, 1658, 1687, 1719, 1728, 1894))
    GROUP BY a.codusur
) a ON u.codusur = a.RCA
WHERE u.nome like 'PMU%'
ORDER BY a.RCA
)
------------------------------------------------------------------------------------------------------------------------------------------------

SELECT 
        1 AS "ORDER",
        'TROCA' AS "§",
        'R$'||TRUNC(NVL((A.VLBONIFIC),0),2) AS "¬"
FROM    
        VL A
WHERE   
        A.CODUSUR = {rca}
------------------------------------------

UNION
SELECT 
        2 AS "ORDER",
        '% TROCA' AS "§",
        TRUNC((NVL(A.VLBONIFIC,1) / NVL(A.VLVENDA,1)) * 100,1)||'%' AS "¬"
FROM    
        VL A
WHERE   
        A.CODUSUR = {rca}
------------------------------------------

UNION
SELECT 
        3 AS "ORDER",
        'FLEX GERADO' AS "§",
        'R$'||TRUNC((NVL(B.GERADO,0) * - 1),2) AS "¬"
FROM    
        FLEX B
WHERE   
        B.CODUSUR = {rca}
------------------------------------------

UNION
SELECT 
        4 AS "ORDER",
        '$ TROCA - FLEX' AS "§",
        'R$'||TRUNC((NVL(A.VLBONIFIC,0) + NVL(B.GERADO,0)),2) AS "¬"
FROM    
        VL A,
        FLEX B
WHERE   
        A.CODUSUR = {rca}
AND        
        B.CODUSUR = {rca}
------------------------------------------

UNION
SELECT 
        5 AS "ORDER",
        '% TROCA - FLEX' AS "§",
        TRUNC(((NVL(A.VLBONIFIC,1) + NVL(B.GERADO,1)) / NVL(A.VLVENDA,1)) * 100,1)||'%' AS "¬"
FROM    
        VL A,
        FLEX B
WHERE   
        A.CODUSUR = {rca}
AND        
        B.CODUSUR = {rca}

------------------------------------------
            ORDER BY "ORDER" ASC