SELECT CODFORNEC,
       FANTASIA AS FANTASIA,
       CODSUPERVISOR, 
       SUBSTR(SUPERV, INSTR(SUPERV, ' ') + 1, INSTR(SUPERV, ' ', INSTR(SUPERV, ' ') + 1) - INSTR(SUPERV, ' ') - 1) AS SUPERV,
       CODUSUR || ' - ' ||
       SUBSTR(nome, INSTR(nome, ' ') + 1, INSTR(nome, ' ', INSTR(nome, ' ') + 1) - INSTR(nome, ' ') - 1) AS RCA,
       SUM(QTCLIPOS) AS QTCLIPOS,
       SUM(PVENDA) AS PVENDA

  FROM (
SELECT 
     PCFORNEC.CODFORNEC,  PCFORNEC.FANTASIA,
 PCPEDC.CODSUPERVISOR  CODSUPERVISOR,
       PCSUPERV.NOME AS SUPERV,
 PCPEDC.CODUSUR  CODUSUR,
       PCUSUARI.NOME,
       COUNT(DISTINCT(PCPEDC.CODCLI)) QTCLIPOS,
       SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2)) PVENDA,
       SUM(PCPEDI.QT) QT,
     SUM(ROUND(NVL(PCPRODUT.PESOBRUTO,0)*NVL(PCPEDI.QT,0),2)) AS TOTPESO,
       SUM(NVL(PCPEDI.QT,0) / DECODE(NVL(PCPRODUT.QTUNIT,0),0,1,NVL(PCPRODUT.QTUNIT,1))) TOTQTUNIT,
       SUM(NVL(PCPEDI.QT,0) / DECODE(NVL(PCPRODUT.QTUNITCX,0),0,1,NVL(PCPRODUT.QTUNITCX,1))) TOTQTUNITCX,
       ROUND(SUM(NVL(PCPRODUT.VOLUME,0)*NVL(PCPEDI.QT,0)) ,2) Volume,
       ROUND(SUM(NVL(PCPRODUT.LITRAGEM, 0)*NVL(PCPEDI.QT,0)) ,2) LITRAGEM,
       COUNT(DISTINCT(PCPEDC.NUMPED)) AS QTPEDIDO,
       COUNT(DISTINCT(PCPEDI.CODPROD)) AS QTMIX,
       COUNT(PCPEDI.CODPROD) NUMITENS,
MAX((/* SQL UTILIZADO PELA ROTINA PCSIS322 RELATORIO(S) - 4 */ SELECT COUNT(P.CODPROD) FROM PONTUAL.PCPRODUT P,PONTUAL.PCDEPTO D WHERE P.CODEPTO = D.CODEPTO
   AND P.CODFORNEC = PCFORNEC.CODFORNEC
                  AND (((P.CODFILIAL IS NULL) OR (P.CODFILIAL = '99')) OR ( P.CODFILIAL IN ('3')))
   AND NVL(P.OBS2,'  ') <> ('FL'))) AS QTMIXCAD,
 0 AS VLMETA,
 0 AS QTMETA,
 0 AS QTPESOMETA,
 0 AS MIXPREV,
 0 AS CLIPOSPREV
FROM PONTUAL.PCPEDI, PONTUAL.PCPEDC, PONTUAL.PCPRODUT, PONTUAL.PCFORNEC, PONTUAL.PCDEPTO, PONTUAL.PCCLIENT,
     PONTUAL.PCUSUARI, PONTUAL.PCATIVI, PONTUAL.PCPRACA, PONTUAL.PCSUPERV
WHERE PCPEDI.NUMPED = PCPEDC.NUMPED
AND PCUSUARI.CODSUPERVISOR NOT IN ('9999')
AND PCPEDC.DATA BETWEEN TO_DATE('{dtIni}', 'DD/MM/YYYY') AND TO_DATE('{dtFim}', 'DD/MM/YYYY')
AND PCPEDI.DATA BETWEEN TO_DATE('{dtIni}', 'DD/MM/YYYY') AND TO_DATE('{dtFim}', 'DD/MM/YYYY')
AND PCPEDC.CODFILIAL IN ('3')
AND PCPEDC.CODSUPERVISOR NOT IN (4)
AND PCPEDC.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
 AND NVL(PCPEDI.BONIFIC, 'N') =  'N' 
AND PCPEDC.CODCLI = PCCLIENT.CODCLI(+)
AND PCCLIENT.CODATV1 = PCATIVI.CODATIV(+)
AND PCPEDC.DTCANCEL IS NULL
AND PCPEDI.CODPROD = PCPRODUT.CODPROD(+)
AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)
AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC(+)
AND  PCPEDC.CODUSUR  = PCUSUARI.CODUSUR 
AND PCPEDC.CODPRACA = PCPRACA.CODPRACA(+)
AND  PCPEDC.CODSUPERVISOR  = PCSUPERV.CODSUPERVISOR 
 AND (PCPEDC.NUMPEDRCA IS NOT NULL OR PCPEDC.NUMPEDRCA = 0) -- GARANTE APENAS PEDIDOS DIGITADOS PELO RCA
AND PCPRODUT.CODFORNEC IN (
  SELECT DISTINCT
    F.CODFORNEC

  FROM
      PONTUAL.PCFORNEC F
  JOIN
      PONTUAL.PCPRODUT P ON F.CODFORNEC = P.CODFORNEC
  JOIN
      PONTUAL.PCPEDI D ON P.CODPROD = D.CODPROD
  WHERE
      D.DATA BETWEEN SYSDATE - 32 AND SYSDATE
)
GROUP BY  
PCFORNEC.CODFORNEC, PCFORNEC.FANTASIA, 
 PCPEDC.CODSUPERVISOR  ,
PCSUPERV.NOME,
 PCPEDC.CODUSUR , 
PCUSUARI.NOME
 HAVING SUM(ROUND(NVL(PCPEDI.QT, 0) * (NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)), 2)) +
      SUM(ROUND(NVL(PCPRODUT.PESOBRUTO, 0) * NVL(PCPEDI.QT, 0), 2)) + 
      SUM(PCPEDI.QT) > 0   
 UNION ALL
   SELECT PCPRODUT.CODFORNEC AS CODFORNEC,  PCFORNEC.FANTASIA,
 PCUSUARI.CODSUPERVISOR,
 PCSUPERV.NOME AS SUPERV,
 PCUSUARI.CODUSUR,
 PCUSUARI.NOME,
 0 AS QTCLIPOS,
 0 AS PVENDA,
 0 AS QT,
 0 AS TOTPESO,
 0 AS TOTQTUNIT,
 0 AS TOTQTUNITCX,
 0 AS Volume,
 0 AS LITRAGEM,
 0 AS QTPEDIDO,
 0 AS QTMIX,
 0 NUMITENS,
 0 AS QTMIXCAD,
 SUM(NVL(PCMETA.VLVENDAPREV,0)) VLMETA,
 SUM(NVL(PCMETA.QTVENDAPREV,0)) QTMETA,
 SUM(NVL(PCMETA.QTPESOPREV,0)) QTPESOMETA,
 SUM(NVL(PCMETA.MIXPREV,0)) MIXPREV,
 SUM(NVL(PCMETA.CLIPOSPREV,0)) CLIPOSPREV
FROM PONTUAL.PCMETA, PONTUAL.PCUSUARI, PONTUAL.PCSUPERV, PONTUAL.PCFORNEC, PONTUAL.PCPRODUT
WHERE PCMETA.CODUSUR = PCUSUARI.CODUSUR
AND PCUSUARI.CODSUPERVISOR NOT IN ('9999')
 AND PCMETA.TIPOMETA = 'P'
 AND PCPRODUT.CODPROD = PCMETA.CODIGO
 AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC(+)
AND PCUSUARI.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR(+)
   AND PCMETA.DATA BETWEEN TO_DATE('{dtIni}', 'DD/MM/YYYY') AND TO_DATE('{dtFim}', 'DD/MM/YYYY')
 AND PCMETA.CODFILIAL IN ('3')
 AND PCUSUARI.CODSUPERVISOR NOT IN (4)
AND pcfornec.CODFORNEC IN (
  SELECT DISTINCT
    F.CODFORNEC

  FROM
      PONTUAL.PCFORNEC F
  JOIN
      PONTUAL.PCPRODUT P ON F.CODFORNEC = P.CODFORNEC
  JOIN
      PONTUAL.PCPEDI D ON P.CODPROD = D.CODPROD
  WHERE
      D.DATA BETWEEN SYSDATE - 32 AND SYSDATE
)
GROUP BY PCPRODUT.CODFORNEC,  PCUSUARI.CODSUPERVISOR, PCUSUARI.CODUSUR, PCFORNEC.FANTASIA, PCSUPERV.NOME, PCUSUARI.NOME
)  
WHERE 1=1  
 and ((nvl(VLMETA, 0) + NVL(QTMETA, 0) + NVL(QTPESOMETA, 0) +
        NVL(MIXPREV, 0) + NVL(CLIPOSPREV, 0)) > 0 OR
        (NVL(QT, 0) + nvl(PVENDA, 0)) > 0)
 group by CODFORNEC, FANTASIA, CODSUPERVISOR, SUPERV, CODUSUR, NOME
ORDER BY 7 DESC
