SELECT 
    A.CODUSUR1 RCA,
    A.CODCLI CODIGO, 
    A.CLIENTE,
    a.dtultcomp,
    A.CGCENT, --REPLACE(REPLACE(REPLACE(A.CGCENT, '.', ''), '-', ''), '/', '') AS CGCENT,
    A.CEPENT CEP,
    A.ENDERENT ||', ' || NUMEROENT ENDEREÇO,
    A.BAIRROENT AS BAIRRO,
    B.NOMECIDADE CIDADE
FROM 
    pontual.PCCLIENT A
JOIN 
    PONTUAL.PCCIDADE B ON A.CODCIDADE = B.CODCIDADE
ORDER BY 
    CODCLI    
