SELECT 
    A.CODUSUR1 RCA,
    A.CODCLI CODIGO, 
    A.CLIENTE,
    A.CGCENT,  --REPLACE(REPLACE(REPLACE(A.CGCENT, '.', ''), '-', ''), '/', '') AS CGCENT,
    A.ENDERENT ||', ' || NUMEROENT ENDEREÇO,
    A.BAIRROENT AS BAIRRO,
    B.NOMECIDADE CIDADE,
    A.dtultcomp
FROM 
    PCCLIENT A
JOIN 
    PCCIDADE B ON A.CODCIDADE = B.CODCIDADE
WHERE 
    A.CODCLI IN (SELECT DISTINCT(CODCLI) FROM PCMOV WHERE DTMOV > SYSDATE-91 AND DTMOV < SYSDATE )
AND
    CODUSUR1 IN (SELECT CODUSUR FROM pcusuari WHERE CODSUPERVISOR in (2,8))    
ORDER BY 
    CODCLI    
