DECLARE
  --v_prefix CONSTANT VARCHAR2(3) := 'NT ';
  cod_fornec NUMBER := 1841;
  cod_distrib NUMBER := 05;
BEGIN
  UPDATE PCPRODUT
  SET CODDISTRIB = cod_distrib
  WHERE codfornec = cod_fornec
  AND DESCRICAO NOT LIKE '%FREEZER%';
END;
/

SELECT CODPROD, DESCRICAO, EMBALAGEM, UNIDADE, CODFORNEC, CODAUXILIAR, CODDISTRIB
FROM PCPRODUT
WHERE codfornec = 1841 
--AND LENGTH(DESCRICAO) > 37
AND DESCRICAO NOT LIKE '%FREEZER%'
ORDER BY DESCRICAO;
