DECLARE
  cod_CODTRIBPISCOFINS NUMBER := 1;
  CODFORNEC_1 NUMBER := 1841;
BEGIN
  UPDATE PCTABPR
  SET PCTABPR.CODTRIBPISCOFINS = cod_CODTRIBPISCOFINS
  WHERE PCTABPR.CODPROD IN (SELECT CODPROD FROM PCPRODUT WHERE CODFORNEC = CODFORNEC_1)
  AND PCTABPR.CODTRIBPISCOFINS != cod_CODTRIBPISCOFINS;
END;

SELECT DISTINCT PCTABPR.CODPROD                
     , PCTABPR.NUMREGIAO                                            
     , PCREGIAO.REGIAO                                  
     , PCTABPR.CODTRIBPISCOFINS                
     , PCTRIBPISCOFINS.DESCRICAOTRIBPISCOFINS
  FROM PCTABPR                                 
     , PCREGIAO                                
     , PCTRIBPISCOFINS
     , PCTRIBUT
     , PCPRODUT
 WHERE ((PCTABPR.NUMREGIAO = PCREGIAO.NUMREGIAO  
   AND PCTABPR.CODTRIBPISCOFINS =  PCTRIBPISCOFINS.CODTRIBPISCOFINS(+) 
   AND ((PCREGIAO.CODFILIAL = :MCODFILIAL) OR 
        (PCREGIAO.CODFILIAL IS NULL) OR        
        (PCREGIAO.CODFILIAL = '99'))
   AND PCTABPR.CODST = PCTRIBUT.CODST(+)) 
   AND ((PCREGIAO.STATUS NOT IN ('I')) OR (PCREGIAO.STATUS IS NULL))) 
   AND PCPRODUT.CODFORNEC = 1623          
   AND PCPRODUT.CODPROD = PCTABPR.CODPROD
   --AND PCTABPR.CODTRIBPISCOFINS != 1
ORDER BY PCTABPR.CODPROD;

