DECLARE
  CODPROD_PRODUTO_MODELO NUMBER := 18804;  -- INSERIR O CÓDIGO DO PRODUTO QUE FOI FEITO O PREENCHIMENTO MANUAL
  CODFORNEC_1 NUMBER := 1894;  -- INSERIR O CÓDIGO DO FORNECEDOR
  
BEGIN

UPDATE PCPRODUT
  SET 
    ( PISCOFINSRETIDO,
      CODFISCAL,
      SITTRIBUT,
      PERICM,
      TIPOMERC,
      CODFISCALBONIFIC,
      PERCREDICMS,
      CODSITTRIBPISCOFINS,
      CODSITTRIBPISCOFINSDEV,
      CODEXCECAOPISCOFINS
    ) =
    (SELECT 
        PISCOFINSRETIDO,
        CODFISCAL,
        SITTRIBUT,
        PERICM,
        TIPOMERC,
        CODFISCALBONIFIC,
        PERCREDICMS,
        CODSITTRIBPISCOFINS,
        CODSITTRIBPISCOFINSDEV,
        CODEXCECAOPISCOFINS
      FROM 
        PCPRODUT
      WHERE 
        CODPROD = CODPROD_PRODUTO_MODELO)
        
WHERE PCPRODUT.CODFORNEC = CODFORNEC_1;
  
END; 

SELECT DISTINCT PCTABPR.CODPROD                
     , PCTABPR.NUMREGIAO                       
     , PCTABPR.CODST                           
     , PCREGIAO.REGIAO                         
     , PCTABPR.PERCDESCSIMPLESNAC              
     , PCTABPR.CODTRIBPISCOFINS                
     , PCTRIBPISCOFINS.DESCRICAOTRIBPISCOFINS
     , NVL(PCTABPR.CALCULARIPI,'S')   CALCULARIPI
     , PCTRIBUT.CODICMTAB
     , PCTRIBUT.CODICM
     , PCTRIBUT.INDICEST
     , PCTRIBUT.CODICMANTECIPADO
     , PCTRIBUT.PERCBASERED
     , PCTRIBUT.PERDESCCUSTO     
     , PCTRIBUT.IVA lkIVA
  FROM PCTABPR                                 
     , PCREGIAO                                
     , PCTRIBPISCOFINS
     , PCTRIBUT                         
 WHERE ((PCTABPR.NUMREGIAO = PCREGIAO.NUMREGIAO  
   AND PCTABPR.CODTRIBPISCOFINS =  PCTRIBPISCOFINS.CODTRIBPISCOFINS(+) 
   AND ((PCREGIAO.CODFILIAL = 3) OR 
        (PCREGIAO.CODFILIAL = 3) OR        
        (PCREGIAO.CODFILIAL = '99'))
   AND PCTABPR.CODST = PCTRIBUT.CODST(+)) 
   AND ((PCREGIAO.STATUS NOT IN ('I')) OR (PCREGIAO.STATUS IS NULL))) 
   AND CODPROD IN (SELECT CODPROD FROM PCPRODUT WHERE CODFORNEC = 850)
ORDER BY PCTABPR.NUMREGIAO

