DECLARE
  CODPROD_PRODUTO_MODELO NUMBER := 18038;  -- INSERIR O CÓDIGO DO PRODUTO QUE FOI FEITO O PREENCHIMENTO MANUAL
  CODFORNEC_1 NUMBER := 1488;  -- INSERIR O CÓDIGO DO FORNECEDOR
BEGIN
UPDATE PCPRODUT
  SET 
    ( PISCOFINSRETIDO,
      CODFISCAL,
      SITTRIBUT,
      PERICM,
      TIPOMERC,
      CODFISCALBONIFIC,
      PERCREDICMS,
      CODSITTRIBPISCOFINS,
      CODSITTRIBPISCOFINSDEV,
      CODEXCECAOPISCOFINS
    ) =
    (SELECT 
        PISCOFINSRETIDO,
        CODFISCAL,
        SITTRIBUT,
        PERICM,
        TIPOMERC,
        CODFISCALBONIFIC,
        PERCREDICMS,
        CODSITTRIBPISCOFINS,
        CODSITTRIBPISCOFINSDEV,
        CODEXCECAOPISCOFINS
      FROM 
        PCPRODUT
      WHERE 
        CODPROD = CODPROD_PRODUTO_MODELO)    
WHERE PCPRODUT.CODFORNEC = CODFORNEC_1;
END;
----------------------------------------------------------------------------------------------------------------
SELECT PCPRODUT.CODPROD, 
       PCPRODUT.PISCOFINSRETIDO, 
       PCPRODUT.CODFISCAL, 
       PCPRODUT.SITTRIBUT, 
       PCPRODUT.PERICM, 
       PCPRODUT.TIPOMERC, 
       PCPRODUT.CODFISCALBONIFIC, 
       PCPRODUT.PERCREDICMS, 
       PCPRODUT.CODSITTRIBPISCOFINS, 
       PCPRODUT.CODSITTRIBPISCOFINSDEV, 
       PCPRODUT.CODEXCECAOPISCOFINS
       --,PCEXPISCOFINS.DESCRICAO
FROM PCPRODUT 
WHERE CODFORNEC = 1488
ORDER BY CODPROD ASC
