DECLARE
  cod_UnVenda NUMBER := 1;
  cod_Fornec NUMBER := 1841;
BEGIN
  UPDATE PCPRODUT
  SET QTUNIT = cod_UnVenda
  WHERE CODFORNEC = cod_Fornec;
END;

SELECT CODPROD,QTUNIT
  FROM PCPRODUT
 WHERE CODFORNEC = 1841;

