DECLARE
  CODPROD_PRODUTO_MODELO NUMBER := 18360;  -- INSERIR O CÓDIGO DO PRODUTO QUE FOI FEITO O PREENCHIMENTO MANUAL
  CODFORNEC_1 NUMBER := 1687;  -- INSERIR O CÓDIGO DO FORNECEDOR
BEGIN
---------------------------------------------------------------------------------------------------------------  
UPDATE PCTABPR A
  SET 
    ( A.CODST,
      A.PERCDESCSIMPLESNAC,
      A.CODTRIBPISCOFINS,
      A.CALCULARIPI
    ) =
    (SELECT 
        B.CODST,
        B.PERCDESCSIMPLESNAC,
        B.CODTRIBPISCOFINS,
        B.CALCULARIPI
      FROM 
        PCTABPR B
      WHERE 
        B.CODPROD = CODPROD_PRODUTO_MODELO
      AND
        B.NUMREGIAO = A.NUMREGIAO)
WHERE A.CODPROD IN (SELECT CODPROD FROM PCPRODUT WHERE CODFORNEC = CODFORNEC_1);
END;
---------------------------------------------------------------------------------------------------------------  
SELECT DISTINCT PCTABPR.CODPROD                
     , PCTABPR.NUMREGIAO                       
     , PCTABPR.CODST                           
     , PCREGIAO.REGIAO                         
     , PCTABPR.PERCDESCSIMPLESNAC              
     , PCTABPR.CODTRIBPISCOFINS                
     , PCTRIBPISCOFINS.DESCRICAOTRIBPISCOFINS
     , NVL(PCTABPR.CALCULARIPI,'S')   CALCULARIPI
     , PCTRIBUT.CODICMTAB
     , PCTRIBUT.CODICM
     , PCTRIBUT.INDICEST
     , PCTRIBUT.CODICMANTECIPADO
     , PCTRIBUT.PERCBASERED
     , PCTRIBUT.PERDESCCUSTO     
     , PCTRIBUT.IVA lkIVA
  FROM PCTABPR                                 
     , PCREGIAO                                
     , PCTRIBPISCOFINS
     , PCTRIBUT                         
 WHERE ((PCTABPR.NUMREGIAO = PCREGIAO.NUMREGIAO  
   AND PCTABPR.CODTRIBPISCOFINS =  PCTRIBPISCOFINS.CODTRIBPISCOFINS(+) 
   AND ((PCREGIAO.CODFILIAL = 3) OR 
        (PCREGIAO.CODFILIAL = 3) OR        
        (PCREGIAO.CODFILIAL = '99'))
   AND PCTABPR.CODST = PCTRIBUT.CODST(+)) 
   AND ((PCREGIAO.STATUS NOT IN ('I')) OR (PCREGIAO.STATUS IS NULL))) 
   AND CODPROD IN (SELECT CODPROD FROM PCPRODUT WHERE CODFORNEC = 1687)
ORDER BY PCTABPR.codprod

