SELECT 
A.SITUACAONFE,
A.PROTOCOLONFE,
A.AMBIENTENFE,
A.NUMNOTA,
A.CODCLI,
A.ENVIADASEMRESPOSTA
,A.*
FROM PCNFSAIDPREFAT A
WHERE A.SITUACAONFE not in (1)
and a.numped = 15221861
--AND A.numcar = 196654
--AND A.DTFAT BETWEEN '07-DEC-2023' AND '09-DEC-2023'


ORDER BY a.CODCLI asc
--103 ESPERANDO RESPOSTA
--101 NOTA CANCELADA
--1000, 204 (duplicidade NF-E), 999 (Erro desconhecido) PENDENTE
--1001 A SER ENVIADO
--1003 NOTA REPROVADA LOCAL AO MONTAR O LOTE


/* PARA NOTA DE ENTRADA
SELECT 
A.SITUACAONFE
,A.*
FROM pcnfent A
WHERE A.NUMNOTA = 428676 */
