SELECT CODFORNEC,
       SUBSTR(FORNECEDOR, 1, 26) AS FORNECEDOR,
       CODSUPERVISOR, 
       SUBSTR(SUPERV, INSTR(SUPERV, ' ') + 1, INSTR(SUPERV, ' ', INSTR(SUPERV, ' ') + 1) - INSTR(SUPERV, ' ') - 1) AS SUPERV,
       CODUSUR,
       SUBSTR(nome, INSTR(nome, ' ') + 1, INSTR(nome, ' ', INSTR(nome, ' ') + 1) - INSTR(nome, ' ') - 1) AS RCA,
       SUM(QTCLIPOS) AS QTCLIPOS,
       SUM(PVENDA) AS PVENDA,
       SUM(QT) AS QT,
       SUM(TOTPESO) As TOTPESO,
       SUM(TOTQTUNIT) AS TOTQTUNIT,
       SUM(TOTQTUNITCX) AS TOTQTUNITCX,
       SUM(Volume) AS Volume,
       SUM(LITRAGEM) AS LITRAGEM,
       SUM(QTPEDIDO) AS QTPEDIDO,
       SUM(QTMIX) AS QTMIX,
       SUM(NUMITENS) AS NUMITENS,
       SUM(QTMIXCAD) AS QTMIXCAD,
       SUM(VLMETA) AS VLMETA,
       SUM(QTMETA) AS QTMETA,
       SUM(QTPESOMETA) AS QTPESOMETA,
       SUM(MIXPREV) AS MIXPREV,
       SUM(CLIPOSPREV) AS CLIPOSPREV
  FROM (
SELECT 
     PCFORNEC.CODFORNEC,  PCFORNEC.FORNECEDOR,
 PCPEDC.CODSUPERVISOR  CODSUPERVISOR,
       PCSUPERV.NOME AS SUPERV,
 PCPEDC.CODUSUR  CODUSUR,
       PCUSUARI.NOME,
       COUNT(DISTINCT(PCPEDC.CODCLI)) QTCLIPOS,
       SUM(ROUND(NVL(PCPEDI.QT,0)*(NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)),2)) PVENDA,
       SUM(PCPEDI.QT) QT,
     SUM(ROUND(NVL(PCPRODUT.PESOBRUTO,0)*NVL(PCPEDI.QT,0),2)) AS TOTPESO,
       SUM(NVL(PCPEDI.QT,0) / DECODE(NVL(PCPRODUT.QTUNIT,0),0,1,NVL(PCPRODUT.QTUNIT,1))) TOTQTUNIT,
       SUM(NVL(PCPEDI.QT,0) / DECODE(NVL(PCPRODUT.QTUNITCX,0),0,1,NVL(PCPRODUT.QTUNITCX,1))) TOTQTUNITCX,
       ROUND(SUM(NVL(PCPRODUT.VOLUME,0)*NVL(PCPEDI.QT,0)) ,2) Volume,
       ROUND(SUM(NVL(PCPRODUT.LITRAGEM, 0)*NVL(PCPEDI.QT,0)) ,2) LITRAGEM,
       COUNT(DISTINCT(PCPEDC.NUMPED)) AS QTPEDIDO,
       COUNT(DISTINCT(PCPEDI.CODPROD)) AS QTMIX,
       COUNT(PCPEDI.CODPROD) NUMITENS,
MAX((/* SQL UTILIZADO PELA ROTINA PCSIS322 RELATORIO(S) - 4 */ SELECT COUNT(P.CODPROD) FROM PCPRODUT P,PCDEPTO D WHERE P.CODEPTO = D.CODEPTO
   AND P.CODFORNEC = PCFORNEC.CODFORNEC
                  AND (((P.CODFILIAL IS NULL) OR (P.CODFILIAL = '99')) OR ( P.CODFILIAL IN ('3')))
   AND NVL(P.OBS2,'  ') <> ('FL'))) AS QTMIXCAD,
 0 AS VLMETA,
 0 AS QTMETA,
 0 AS QTPESOMETA,
 0 AS MIXPREV,
 0 AS CLIPOSPREV
FROM PCPEDI, PCPEDC, PCPRODUT, PCFORNEC, PCDEPTO, PCCLIENT,
     PCUSUARI, PCATIVI, PCPRACA, PCSUPERV
WHERE PCPEDI.NUMPED = PCPEDC.NUMPED
AND PCUSUARI.CODSUPERVISOR NOT IN ('9999')
AND PCPEDC.DATA BETWEEN '{dtIni}' AND '{dtFim}'
AND PCPEDI.DATA BETWEEN '{dtIni}' AND '{dtFim}'
AND PCPEDC.CODFILIAL IN ('3')
AND PCPEDC.CODSUPERVISOR IN (2,8)
AND PCPEDC.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
 AND NVL(PCPEDI.BONIFIC, 'N') =  'N' 
AND PCPEDC.CODCLI = PCCLIENT.CODCLI(+)
AND PCCLIENT.CODATV1 = PCATIVI.CODATIV(+)
AND PCPEDC.DTCANCEL IS NULL
AND PCPEDI.CODPROD = PCPRODUT.CODPROD(+)
AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO(+)
AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC(+)
AND  PCPEDC.CODUSUR  = PCUSUARI.CODUSUR 
AND PCPEDC.CODPRACA = PCPRACA.CODPRACA(+)
AND  PCPEDC.CODSUPERVISOR  = PCSUPERV.CODSUPERVISOR 
AND PCPRODUT.CODFORNEC IN (588,1658,1634,1627,1894,1687,1225,1488,1727,1841,1728,1719,1321,850,1895,872,1623,1607,1541)
GROUP BY  
PCFORNEC.CODFORNEC, PCFORNEC.FORNECEDOR, 
 PCPEDC.CODSUPERVISOR  ,
PCSUPERV.NOME,
 PCPEDC.CODUSUR , 
PCUSUARI.NOME
 HAVING SUM(ROUND(NVL(PCPEDI.QT, 0) * (NVL(PCPEDI.PVENDA, 0) + NVL(PCPEDI.VLOUTRASDESP, 0) + NVL(PCPEDI.VLFRETE, 0)), 2)) +
      SUM(ROUND(NVL(PCPRODUT.PESOBRUTO, 0) * NVL(PCPEDI.QT, 0), 2)) + 
      SUM(PCPEDI.QT) > 0   
 UNION ALL
   SELECT PCPRODUT.CODFORNEC AS CODFORNEC,  PCFORNEC.FORNECEDOR,
 PCUSUARI.CODSUPERVISOR,
 PCSUPERV.NOME AS SUPERV,
 PCUSUARI.CODUSUR,
 PCUSUARI.NOME,
 0 AS QTCLIPOS,
 0 AS PVENDA,
 0 AS QT,
 0 AS TOTPESO,
 0 AS TOTQTUNIT,
 0 AS TOTQTUNITCX,
 0 AS Volume,
 0 AS LITRAGEM,
 0 AS QTPEDIDO,
 0 AS QTMIX,
 0 NUMITENS,
 0 AS QTMIXCAD,
 SUM(NVL(PCMETA.VLVENDAPREV,0)) VLMETA,
 SUM(NVL(PCMETA.QTVENDAPREV,0)) QTMETA,
 SUM(NVL(PCMETA.QTPESOPREV,0)) QTPESOMETA,
 SUM(NVL(PCMETA.MIXPREV,0)) MIXPREV,
 SUM(NVL(PCMETA.CLIPOSPREV,0)) CLIPOSPREV
FROM PCMETA, PCUSUARI, PCSUPERV, PCFORNEC, PCPRODUT
WHERE PCMETA.CODUSUR = PCUSUARI.CODUSUR
AND PCUSUARI.CODSUPERVISOR NOT IN ('9999')
 AND PCMETA.TIPOMETA = 'P'
 AND PCPRODUT.CODPROD = PCMETA.CODIGO
 AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC(+)
AND PCUSUARI.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR(+)
   AND PCMETA.DATA BETWEEN  '{dtIni}' AND '{dtFim}'
 AND PCMETA.CODFILIAL IN ('3')
 AND PCUSUARI.CODSUPERVISOR IN (2,8)
AND pcfornec.CODFORNEC IN (588,1658,1634,1627,1894,1687,1225,1488,1727,1841,1728,1719,1321,850,1895,872,1623,1607,1541)
GROUP BY PCPRODUT.CODFORNEC,  PCUSUARI.CODSUPERVISOR, PCUSUARI.CODUSUR, PCFORNEC.FORNECEDOR, PCSUPERV.NOME, PCUSUARI.NOME
)  
WHERE 1=1  
 and ((nvl(VLMETA, 0) + NVL(QTMETA, 0) + NVL(QTPESOMETA, 0) +
        NVL(MIXPREV, 0) + NVL(CLIPOSPREV, 0)) > 0 OR
        (NVL(QT, 0) + nvl(PVENDA, 0)) > 0)
 group by CODFORNEC, FORNECEDOR, CODSUPERVISOR, SUPERV, CODUSUR, NOME
ORDER BY PVENDA DESC
